# WLAN
wifi_ssid: "DEIN_WLAN_NAME"
wifi_password: "DEIN_WLAN_PASSWORT"

# AP:
ap_ssid: "AP_SSID"
ap_password: "AP_FALLBACK_PASSWORT"
   
# mqtt
mqtt_broker: 192.168.1.10
mqtt_username: "DEIN_MQTT_BENUTZER"
mqtt_password: "DEIN_MQTT_PASSWORT"
